#+TITLE: Runtime Broswer for Virtual Labs 
#+AUTHOR: VLEAD
#+DATE: [2018-01-16 Tuesday]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Runtime Browser for Virtual Labs

** Overview and Motivation
   Virtual Labs is providing an easier approach to access
   Virtual Labs and its experiments using runtime browser
   through VirtualBox.  Installing VirtualBox will eliminate
   the need for installing dependencies such as Adobe Flash,
   Java3D, etc. on user machine.  The VirtualBox that is
   provided by Virtual Labs can be used for both Online and
   Offline (College Cloud) versions of Virtual Labs.
   
** Audience
   Virtual Lab users.

** Systems Requirements
   Minimum systems requirements.
   1) Operating Systems (OS) - Any OS that supports Oracle
     VirtualBox or VMWare Workstation. The system should
     have the provision to support Virtualization
     Technology.
   2) 4GB RAM.
   3) Dual Core processor.

** VirtualBox installation steps

    1) Visit  the VirtualBox  provider website.  Please note
       that installation needs to be done only once.
    2) Choose the appropriate VirtualBox version based on
       the Operating System ( OS ) installed on the machine.
    3) Download the selected VirtualBox.
    4) VirtualBox installation steps for Windows OS :
         Double click on .exe file.
         Follow the instructions appearing on installation wizard.
         After installation, ensure that a VirtualBox icon is created on the desktop.
    Steps 6,7 and 8 are installation step examples for CentOS-6.x, Ubuntu 14.04. and Mac OS respectively. These installation steps will vary based on the version of the OS installed on the user machine. Please follow the link for appropriate steps.
    VirtualBox installation steps for CentOS-6.X OS :
        Download RPM package using the following command :
        wget http://download.virtualbox.org/virtualbox/5.1.6/VirtualBox-5.1-5.1.6_110634_el6-1.x86_64.rpm
        Install VirtualBox using the following command :
        sudo rpm -i VirtualBox-5.1-5.1.6_110634_el6-1.x86_64.rpm
    VirtualBox installation steps for Ubuntu 14.04 :
        Download RPM package using the following command :
        wget http://download.virtualbox.org/virtualbox/5.2.0/virtualbox-5.2_5.2.0-118431~Ubuntu~trusty_amd64.deb
        Install VirtualBox using the following command :
        sudo dpkg -i virtualbox-5.2_5.2.0-118431~Ubuntu~trusty_amd64.deb
    VirtualBox installation steps for Mac OS :
        Follow the link to download the VirtualBox for Mac and save it.
        Double click on downloaded (.dmg) file and follow the instructions for installation.

Virtual-Labs VirtualBox import steps

    Follow the link to download and save the file ubuntu-14.04-college-cloud.ova. Note that import steps need to be performed only once.
    Double click on the ubuntu-14.04-college-cloud.ova file. An import window will appear.
    Import the file ubuntu-14.04-college-cloud.ova and follow the steps to install it. This may take 5 to 10 minutes.
    On completion of step 3, select the ubuntu-14.04-college-cloud from the VirtualBox window. Allocate the Processor and Memory/RAM size from the Settings menu appropriately, based on the system configuration of the user machine.
    Recommended Settings for the imported box :
        Processor --> 1
        Memory/RAM size --> 2GB

Using VirtualBox to run Virtual Labs

    Windows Users: Double click the VirtualBox icon on the desktop to start the VirtualBox.
    Linux Users (CentOS, Debian, Ubuntu, etc): Search for VirtualBox on user machine and select it.
    Start ubuntu-14.04-college-cloud box.
    Login to ubuntu-14.04-college-cloud using the following credentials:
    User Name : College Cloud
    Password : cc
    Open Firefox and type vlabs.ac.in to use Virtual Labs.
    The above steps need to be followed each time Virtual Labs is accessed through the VirtualBox.

Note:

    Please use only Firefox ( provided in the VirtualBox ) to use Virtual Labs.
    Do not upgrade Firefox version in the VirtualBox.

