#+AUTHOR: VLEAD
#+DATE: [2018-01-16 Tuesday]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil



* General Information

** Phone Numbers :
   General Information :
   011-64674687
   Development/Outreach :
   +91 9177792945
   
** Email address :
   support@vlabs.ac.in
   
** Mailing Address :
   Room No:206/II A,
   Bharti School of Telecom,
   Indian Institute of Technology, Delhi,
   Hauz Khas, New Delhi - 110016 (India)
   
** Engineering and Architecture Division : 
   Room No:B6-204,
   Vindhya C6, VLEAD, IIIT-H, Gachibowli,
   Hyderabad - 500032
   
* Community
** Internet Relay Chat (IRC)

*** IRC Channels on [[http://freenode.net/][Freenode]] network
    #vlead :: used by the community developing the
    infrastructure for Virtual Labs.
    #vlabs-engineers ::
    used by lab developers and integrators.  Channel open
    from 10am to 5pm GMT+5:30.

*** Help with IRC Chat
    This tutorial lists all the information in using IRC for communication.
    [[http://xchat.org/][xchat]] which can be downloaded and installed is a recommended client for conducting communication on IRC channels.

** Mailing Lists

*** Google Groups
    A mailing list, [[https://groups.google.com/a/vlabs.ac.in/forum/?hl=en#!forum/engineers][engineers]], is used by all the engineers
    who contribute to the development of Virtual Labs. A
    concrete feature requirement could evolve out of a
    discussion on this mailing list.

    [[https://groups.google.com/a/vlabs.ac.in/forum/?hl=en#!forum/engineers][Subscribe/Unsubscribe]] to the engineers mailing list.

*** Engineers' Forum
    This [[https://github.com/virtual-labs/engineers-forum/issues][forum]] is conducted using GitHub [[https://guides.github.com/features/issues/][issues]]. Any issue
    faced with the development of Virtual Labs is raised in
    this forum. A GitHub handle is necessary to create an
    issue.

*** Announcements
    All the announcements related to Virtual Labs are made
    in the [[https://groups.google.com/a/vlabs.ac.in/forum/?hl=en#!forum/announce][announce]] mailing list.  
    [[https://groups.google.com/a/vlabs.ac.in/forum/?hl=en#!forum/announce][Subscribe/Unsubscribe]] to the [[https://groups.google.com/a/vlabs.ac.in/forum/?hl=en#!forum/announce][announce]] mailing list.
