** Virtual Labs

   Q1. What are Virtual Labs?  

       Virtual Labs are intended to augment the learning of
       science and engineering subjects through performing
       experiments. The experiments are designed either as
       simulations or as remote triggered. A remote
       triggered lab allows a user to connect to real
       equipment using a web browser. There are currently
       around 150 and labs and 1500 experiments at various
       stages of development and deployment. They are
       currently hosted at vlabs.ac.in. Virtual Labs is an
       initiative of Ministry of Human Resources, India.
     
   Q2. What are the objectives of the Virtual Labs?

       The broad objectives of the 'Virtual Lab' as stated
       in website are:

       1. To provide remote access to Labs in various
          disciplines
       2. To arouse curiosity in students and help them
          learn concepts through remote experimentation
       3. To provide a complete 'Learning Management System'
          (LMS) around the Virtual-labs 
       
          a. access to web-resources, videos, animated
             demonstrations and 
          b. self evaluation
      4. To provide access to resources available to only a
         limited number of users due to constraints of time
         and physical locations.

      Q3. What are the various types of Virtual Labs?

          There are two types of Virtual Labs:

          **Simulation Based Virtual Labs:** In these Virtual
          Labs, the experiments are modeled using
          mathematical equations. The simulations are
          carried out remotely at a high end server, and the
          results are communicated to the student over the
          internet. This class of Virtual Labs, at best,
          mimics the real-world
          scenarios/experiments. Simulation based Virtual
          Labs are scalable and can cater to a large number
          of simultaneous users.

          **Remote Triggered Virtual Labs:** In these Virtual
          Labs, the actual experiments are triggered
          remotely. The output of the experiment (being
          conducted remotely) is communicated back to the
          student over the internet. This class of Virtual
          Labs, gives the student the output of real-time
          experiments. Remote Triggered Virtual Labs are
          difficult to scale and can cater to a limited
          number of users. Typically, time-slots are booked
          before conducting such experiments.

    Q4. Who are the intended users of the Virtual Labs? 
        The intended beneficiaries of the projects are:

    1. All students and Faculty Members of Science and
       Engineering Colleges who do not have access to good
       lab-facilities and/or instruments.
    2. High-school students, whose inquisitiveness will be
       triggered, possibly motivating them to take up
       higher-studies.
    3. Researchers in different institutes who can
       collaborate /share equipment and resources.
    4. Different engineering colleges, who can benefit from
       the content and related teaching resources. The
       project has completely fulfilled the requirements of
       the targeted beneficiaries (and even gone beyond). An
       eco-system has evolved around Virtual Labs, where the
       community has become involved in evolving and
       benefitting from the project.
    
    Q5. How can I access the Virtual Labs?

        All Virtual Labs can be accessed through a common
        website: [[https://www.vlabs.ac.in][vlabs]] At the user end, a PC and broadband
        connectivity enables the user to access Virtual
        Labs.

    Q6. Is it free to use?
        Yes, it is free of cost to the user.

    Q7. How I can find lab of my interest?  

        The Virtual labs are divided into two categories on
        the Virtual Labs home page (www.vlabs.ac.in)

        [[https://vlabs.ac.in][All Labs (Domain Wise)]]

        [[https://vlabs.ac.in][All Labs (Institute Wise)]]

        [[https://vlabs.ac.in/][All Labs on Open edX]]

        You can click on any of the above links which are on
        the main menu under Labs option to find out labs of
        your perfernce .  For some of the labs, you will
        first have to [[https://openedx.vlabs.ac.in/register][register]] prior to conducting the
        experiments.

   Q8. What are the software requirements for Virtual Labs?
       Download Links for all the software required to use
       the labs are provided on each lab's homepage
       (wherever required). Please click on [[http://vlabs.ac.in/pre-requisites.html][pre-requisites]]
       link to know the information about how to download,
       install and use the software.

   Q9. What are the system configuration needed to run
       Workshops ?  

       System configuration required for running Virtual
       Labs:
       1. Browser: Firefox, Chrome
       2. Plugins: Flash, Java 1.6 version, and IcedTea
       3. JavaScript should be enabled on the browser
       4. No pop-up blockers
       5. Internet connection (2-4 mbps)
       6. Need an Electronics Faculty while running some of the
          adders, multiplexers experiments.

       For more details, please follow the [[http://vlabs-about.vlabs.ac.in/#sec-2][link]]

   Q10. Our college internet network has firewalls. Should
        any specific care be taken?

        If Internet network operates behind a firewall, the
        communication ports to facilitate VLab network
        traffic should be open. Specifically ports 3306,
        5900, 5902, and 8700 will need to be opened.

   Q11. Can I use Virtual Labs at all times?

        Virtual Labs are divided into two categories, namely
        remote triggered labs and the simulation based
        labs. You can use the remote triggered labs, as per
        the time mentioned on the website. The simulation
        based labs are available 24x7 including weekends.

   Q12. Does the Virtual Lab provide the LMS that the
        objectives mention?  

        Virtual Lab project provides a complete Leaning
        Management System. For most users, Virtual Lab
        provides all the relevant material at one place
        including the Objectives of the Experiment,
        Procedure, Lab manual, Pre- and Post-experiment
        quizzes, additional Lab resources, in addition to
        the Virtual Lab experiment. Most labs also have an
        associated question bank.

   Q13. How do I register for using the Virtual Labs? 

        As mentioned earlier, Virtual Labs are divided into
        two categories: simulation based labs and remote
        triggered labs. Registration requirements are
        different for the two categories.

        Simulation based Labs: Many of the simulation based
        labs (marked with '*' require one-time registration
        [[https://vlabs.ac.in/][link]]. You can register by clicking the [[https://openedx.vlabs.ac.in/register][register]]
        button on the top right corner of any Virtual Labs
        Page. However some labs that do not require
        registration can be directly accessed by following
        the lab links.
    
        Remote Triggered Labs: To access a remote triggered
        lab, a user has to book a slot. For booking a slot,
        you have to register yourself first and then book a
        slot from the slot chart. All the available /booked
        slots can be viewed on this chart. Once a request
        for slot-booking is made, all the information
        regarding the user id, password and the slot booked
        will be sent to the user's email address provided by
        the user at the time of registration. Once
        registered, a user can login using the same
        credentials every time. This registration has to be
        done by the user separately for each of the remote
        triggered virtual labs.


    Q14. I already have a Physical Lab in my
         college/institute. What benefit will Virtual Lab
         provide?

         Virtual Lab is a complete Learning Management
         System. All the relevant information including the
         theory, lab-manual, additional web-resources,
         video-lectures, animated demonstrations and
         self-evaluation are available at a common
         place. Virtual Labs can be used in a complementary
         fashion to augment the efficacy of theory-based
         lectures. Small projects can also be carried out
         using some of the Virtual Labs. Virtual Labs can be
         effectively used to give lab-demonstrations to
         large classes.

   Q15. How does one derive the maximum benefit from Virtual
        Labs?

        In order to derive maximum learning experience, the
        users are advised to first read all the instructions
        for conducting the labs. There are 'step-by-step'
        instructions available in each lab to assist the
        users.

   Q16. When I do an experiment how do I know if the
        experiment I did is done correctly?

        Virtual Labs will provide to the students the result
        of an experiment by one of the following methods (or
        possibly a combination):

        1. Modelling the physical phenomenon by a set of
           equations and carrying out simulations to yield
           the result of the particular experiment.
        2. Providing a corresponding measurement data for
           the Virtual Lab experiment based previously
           carried out measurements on an actual system.
        3. Remotely triggering an experiment in an actual
           lab and providing the student the result of the
           experiment through the computer interface.

   Q17. How can a college conduct a Virtual Lab Workshop?
        
        For details, please follow the [[http://vlabs-about.vlabs.ac.in/#sec-2][link]]

   Q18. Whom can I contact if I get stuck while using
        Virtual Labs?  
        
        You can email your concerns/queries to the Virtual
        Labs team at users@vlabs.ac.in. Also,you can call
        directly on the hotline number 011-64674687 for
        help.

   Q19. How can I contribute to the FAQ?  
       
        Drop a mail to poc-vlead@vlabs.ac.in with Questions
        (and Answers).

   Q20. How can I contribute to Virtural Labs?

        vlabs-dev is the main portal for Virtual Labs
        Development. Please visit the [[http://vlabs-dev.vlabs.ac.in/community/contributing.html][contributing]] section
        of the [[http://vlabs-dev.vlabs.ac.in/][vlabs-dev]] portal.

** Virtual Labs College Cloud Edition
   Q1. What is a Virtual Labs College Cloud Edition ?

      Virtual Labs College Cloud Edition is the
      Portable-Edition of Virtual Labs. It offers the
      offline version of Virtual labs, experiments and
      theoretical content. This edition addresses the lack
      of internet access or poor internet connectivity
      across different institutes/colleges. It results in a
      very cost-effective Learning Management System.

   Q2. Why would my college need Virtual Labs College Cloud
       Edition?

       Virtual Labs College Cloud Edition currently has
       about [[http://community.vlabs.ac.in/docs/user-manuals/college-cloud/labs-on-college-cloud/list-of-labs-in-college-cloud.html#list-of-labs][75]] labs (750+ experiments) across multiple
       disciplines. It aims at providing remote access to
       labs for Science and Engineering students. Simulation
       based experimentation would now be possible without
       the internet facility. This initiative would make the
       labs developed by [[https://vlabs.ac.in/][top technical institutes]] accessible
       to every college.

   Q3. Who can use Virtual Labs College Cloud Edition?

       All interested faculty and students of the
       college/institutes can use Virtual Labs College Cloud
       Edition.

   Q4. Would my college need any internet connectivity to
       use the Virtual Labs College Cloud Edition ?

       No,however it is encouraged that the College Cloud
       server be connected to the internet on a regular
       basis to facilitate log collection.

   Q5. What are the system requirements for using the
       Virtual Labs College Cloud Edition ?

       For a offline Virtual Labs College Cloud Edition to
       be used at your institute/college, your
       college/institute should be a Central/State
       University approved by AICTE/UGC. It would also have
       to meet the following system requirements:

       **System Configuration (recommended)**

         - Processor : Intel(R) Core(TM) i7-3770 , CPU with
           3.40GHz(Model : intel-db75en)
         - RAM : 16 GB
         - SMPS : 600 W
         - CPUs: 8
         - MotherBoard wattage: 77 W
         - 500 GB SATA
         - WiFi Router : WiFi router which could serve 30-80
           users
         - Computer Lab with at least 30-80 Systems/Desktops
         - Network Input ( Network Switch , from where all
           the labs would obtain DHCP IP) to Computer Lab
           machines/Desktops.
         - This would make College Cloud accessible over the
           LAN network providing better results
         - System Administrator with basic knowledge of
           CentOS operating systems and networking.

   Q6. What is the SLA (service level agreement ) for using
       Virtual Labs College Cloud Edition ?
   
       1. For the above given System Configuration, you
          could work with 3-5 labs at a time catering 20-30
          users.
       2. Virtual Labs College Cloud server would not be
          connected to the internet while labs are being
          accessed over the College Cloud.
       3. College Cloud server should be connected to the
          internet on a regular basis to facilitate log
          collection.
       4. Videos of the labs would not be accessible from
          the Virtual Labs College Cloud Edition.
   
   Q7. How can I request for a Virtual Labs College Cloud
       Edition Workshop to be conducted at my college?

       You can request for a Virtual Labs College Cloud
       Edition workshop to be conducted at your college by
       following the below steps :

       1. Please make sure that the requirements (Offline
          Virtual Labs College Cloud version) are met.
       2. Fill the [[https://docs.google.com/a/vlabs.ac.in/forms/d/e/1FAIpQLScvUGaE6ln6JzeIVc2CqTXwac_R69WhzoM5TrW6y99hFB6nbw/viewform?embedded=true][Expression]] of Interest form.
       3. You will be contacted by the Virtual Labs Outreach
          Team.
       4. On confirmation from the Virtual Labs team on the workshop
          date (as filled in the
          [[https://docs.google.com/a/vlabs.ac.in/forms/d/e/1FAIpQLScvUGaE6ln6JzeIVc2CqTXwac_R69WhzoM5TrW6y99hFB6nbw/viewform?embedded=true][Expression
          of Interest]]) , you will need to download the checklist
          [[./forms/Prerequisite-college-cloud-version-workshop.docx][form]] for offline Virtual Labs College Cloud version. You
          would need mail the duly fill/scanned form to
          workshops@vlabs.ac.in .
      5. On receipt of the above form, Virtual Labs Outreach
         Team would conduct the workshop on the scheduled
         date at your premises.
  Q8. How can I request for a Virtual Labs College Cloud
      Edition for my college?

      You can request for a Virtual Labs College Cloud
      Edition for your college by following the below
      steps :

      1. Please make sure that the requirements (Offline
         Virtual Labs College Cloud version) are met.
      2. Fill the [[https://docs.google.com/a/vlabs.ac.in/forms/d/e/1FAIpQLSeiV1j8eLGFDgf0ZS1bQFOpAEEa8Nm1pptO46HA9JydUc2-iQ/viewform?embedded=true][Expression]] of Interest form.
      3. On receipt of the above form, you will be contacted
         by the Virtual Labs Outreach Team.

  Q9. How do I deploy Virtual Labs College Cloud Edition ?  
  
      Virtual Labs College Cloud Edition could be deployed by
      following the steps described in the
      [[http://community.vlabs.ac.in/docs/user-manuals/college-cloud/installation-manual.html][installation
      manual]].

  Q10. Where can I get support on Virtual Labs College Cloud
       Edition ?  

       You can get help on Virtual Labs College Cloud Edition and
       other Virtual Labs related issues by posting on the mailing
       list for [[https://groups.google.com/a/vlabs.ac.in/forum/?hl=en#%21forum/engineers][engineers]] contributing to Virtual
       Labs. [[https://groups.google.com/a/vlabs.ac.in/forum/?hl=en#%21forum/engineers][Subscribe/Unsubscribe]] to the < a
       href="https://groups.google.com/a/vlabs.ac.in/forum/?hl=en#%21forum/engineers">engineers
       mailing list. You can also post your queries to the < a
       href="https://plus.google.com/communities/104131148292250423165">teacher's
       community .


  Q11. Do I have to pay for the Virtual Labs College Cloud Edition ?
    
       No, the lab content is free of charge. However, the
       college would have to incur the cost of the systems
       and their maintenance.

  Q12. What are the terms and conditions for using Virtual
       Labs College Cloud Edition in your college ?

       There is no financial liability on any party for
       using Virtual Labs. It is free to use.

         - The Institute/College cannot charge students for
           the use of Virtual Labs.
         - The institute/college must nominate a single
           point of contact for all logistical and technical
           coordination between the institute and Virtual
           Labs.

** Expression of Interest for Workshops

   Q1. What is a Virtual Labs Workshop ?  
    
       Virtual Labs Team organizes workshops with hands-on
       practice sessions on Virtual Labs (both Offline
       College Cloud version and Online version) for
       interested Science & Engineering Institutions. The
       sessions are conducted for faculty members and
       students of interested institutes upon expression of
       their interest for Virtual Labs workshop.

   Q2. Who can request for a Virtual Labs Workshop ?

       Workshops can be requested by faculty members or
       college/institute management of the interested
       Science & Engineering Institutions.

   Q3. Who can participate in the workshop ?

       All interested faculty and students of the
       college/institutes can participate in the workshop.

   Q4. Are there different versions of the Virtual Labs
       Workshop ?

       There are two versions of the Virtual Labs workshop :
       Online Version and Offline Virtual Labs College Cloud
       Edition.  

       Virtual Labs College Cloud Edition is the Offline and
       Portable Edition for Virtual Labs. It offers an
       offline version of Virtual Labs, experiments and
       theoretical content. This edition addresses the lack
       of internet access or poor internet connectivity
       across different institutes/colleges. It results in a
       very cost-effective Learning Management System. This
       edition could be used effectively when specific
       experiments are being done by students of a class,
       for specific course requirements. These labs are not
       dependent on the quality and availability of the
       Internet and hence would be a stable edition for
       longer sessions.

       On the other hand the online version is available at
       all times but is dependent on a good Internet
       link. Any of the 1700+ odd experiments could be
       performed at all times providing a good opportunity
       for continuous usage. Thus, it is suggested that the
       college cloud edition and the online versions should
       be used together in a college. On completion of the
       demonstrations and hands-on sessions, the faculty
       members and the students are encouraged to submit the
       feedback form to the Virtual Labs team. These forms
       are compiled and analyzed for further improvements in
       the Virtual Labs.

   Q5. What are the system requirements for the Online
       version of the Virtual Labs Workshop ?

       For a Online version of the Virtual Labs workshop to
       be conducted, your college/institute would have to
       meet the following system requirements:

       **System configuration (Recommended)**

          - Browser: Firefox, Chrome
          - Plugins: Flash, Java 1.6 version, and IcedTea
          - JavaScript should be enabled on the browser
          - No pop-up blockers
          - Internet connection (1 Mbps) and a multimedia projector

   Q6. What are the other requirements for the Online
       version of the Virtual Labs Workshop ?

       For a Online version of the Virtual Labs workshop to
       be conducted , your college/institute would have to
       meet the following requirements:

        - The college/institute should be a Central/State
          University or institute/college approved by AICTE/UGC.
        - The college/institute must have an auditorium with
          a seating capacity of at least 100 and a
          designated/common lab space having 35 PCs or more.
        - In the event that the Internet operates behind a
          firewall, the specific communication ports 3306,
          5900, 5902, and 8700 would need to be opened to
          facilitate Virtual Labs network traffic.
        - [[https://www.java.com/en/download/][Java]] must be downloadable through the Internet and
          Gmail must be accessible.
        - [[http://vlabs.ac.in/][Vlabs web page]] should be accessible from the
          browser.
        - Registration should be successful from
          [[https://openedx.vlabs.ac.in/register][registration]] page.
        - Lab-level and experiment-level feedback links (
          within a lab) should be working within the
          institute network.

  Q7. What are the system requirements for the Virtual Labs
      College Cloud Edition Workshop ?

     For a offline Virtual Labs College Cloud Edition
     Workshop to be conducted, your college/institute would
     have to meet the following system requirements:

     **System Configuration (recommended)**

       - Processor : Intel(R) Core(TM) i7-3770 , CPU with
         3.40GHz (Model : intel-db75en)
       - RAM : 16 GB
       - SMPS : 600 W
       - CPUs: 8
       - MotherBoard wattage: 77 W
       - 500 GB SATA
       - WiFi Router : WiFi router which could serve 30-80
         users
       - Network Input ([[https://en.wikipedia.org/wiki/Network_switch][Network Switch]] , from where all the
         labs would obtain DHCP IP) to Computer Lab
         machines/Desktops.
       - Computer Lab with at least 30-80 Systems/Desktops
       - This would make College Cloud accessible over the
         LAN network providing better results.
      -  System Administrator with basic knowledge of CentOS
         operating systems and networking.

  Q8. How can I request for a Workshop to be conducted at my
      college?

      You can request for a workshop to be conducted at your
      college by following the below steps :

      1. Please make sure that the requirements (offline
         College Cloud version/online version) are met.
      2. Fill the [[https://docs.google.com/a/vlabs.ac.in/forms/d/e/1FAIpQLScvUGaE6ln6JzeIVc2CqTXwac_R69WhzoM5TrW6y99hFB6nbw/viewform?embedded=true][Expression of Interest]] form.
      3. You would be contacted by the Virtual Labs Outreach
         Team.
      4. On confirmation from the Virtual Labs team on the
         workshop date (as filled in the Expression of
         Interest) , you would need to download a checklist
         [[./forms/Prerequisite-online-version-workshop.docx][form]] for online version and/or a checklist [[./forms/Prerequisite-college-cloud-version-workshop.docx][form]] for
         offline College Cloud version. You would then need
         to mail the duly fill/scanned form to
         workshops@vlabs.ac.in .
      5. On receipt of the above form, Virtual Labs Outreach
         Team would conduct the workshop on the scheduled
         date at your premises.

  Q9. What are the other requirements for the Virtual Labs
      College Cloud Edition Workshop ?
   
      For a offline Virtual Labs College Cloud Edition
      Workshop to be conducted, your college/institute would
      have to meet the following system requirements:

      - The college/institute should be a Central/State
        University or institute/college approved by AICTE/UGC.
      - The college/institute must have an auditorium with a
        seating capacity of at least 100 and a
        designated/common lab space having 35 PCs or more.

  Q10. Can I request for both Online and Offline Virtual
       Labs College Cloud Edition Workshop version to be
       conducted at my college ?

       Yes, both versions of workshop can conducted at your
       college. However, you would need to ensure that the
       requirements for both versions are met.

  Q11. What would be covered in the workshop ?  

       An overview ,demo and hands-on of two Virtual Labs
       will be covered during the workshop.

  Q12. Does my college have to pay for the workshops ?

     College/Institute will have to pay for the travel,lodging and
     boarding for two Virtual Labs representatives.

  Q13. Where can I get support on Virtual Labs Workshops ?

       You can get help on workshops and other Virtual Labs
       related issues by posting on the mailing list for
       [[https://groups.google.com/a/vlabs.ac.in/forum/?hl=en#%21forum/engineers][engineers]] contributing to Virtual Labs. You may
       [[https://groups.google.com/a/vlabs.ac.in/forum/?hl=en#%21forum/engineers][Subscribe/Unsubscribe]] to the [[https://groups.google.com/a/vlabs.ac.in/forum/?hl=en#!forum/engineer][engineers]] mailing
       list. You can also post your queries to the
       [[https://plus.google.com/communities/104131148292250423165][teacher's community]] .

  Q14. What are the terms and conditions for using Virtual
       Labs in your college ?

       There is no financial liability on any party for
       using Virtual Labs. It is free to use.

       - The Institute/College cannot charge students for
         the use of Virtual Labs.
       - The institute/college must nominate a single point
         of contact for all logistical and technical
         coordination between the institute and Virtual
         Labs.

  Q15. Where have the Virtual Labs workshops been conducted
       ?  

       Please follow the [[http://outreach.virtual-labs.ac.in/ws_details#/ws-list][link]] to view the list of colleges
       where Virtual Labs Workshops have been conducted.
