#+TITLE: Virtual Labs 
#+AUTHOR: VLEAD
#+DATE: [2018-01-16 Tuesday]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

** Virtual Labs

Q1. What are Virtual Labs?  

Virtual Labs are intended to augment the learning of science and
engineering subjects through performing experiments. The experiments
are designed either as simulations or as remote triggered. A remote
triggered lab allows a user to connect to real equipment using a web
browser. There are currently around 150 and labs and 1500 experiments
at various stages of development and deployment. They are currently
hosted at vlabs.ac.in. Virtual Labs is an initiative of Ministry of
Human Resources, India.

Q2. What are the objectives of the Virtual Labs?

The broad objectives of the 'Virtual Lab' as stated in website are:

   1. To provide remote access to Labs in various disciplines
   2. To arouse curiosity in students and help them learn concepts
      through remote experimentation
   3. To provide a complete 'Learning Management System' (LMS) around
      the Virtual-labs 
      a. access to web-resources, videos, animated demonstrations and 
      b. self evaluation
   4. To provide access to resources available to only a limited
      number of users due to constraints of time and physical
      locations.

Q3. What are the various types of Virtual Labs?

There are two types of Virtual Labs: 

Simulation Based Virtual Labs: In these Virtual Labs, the experiments
are modeled using mathematical equations. The simulations are carried
out remotely at a high end server, and the results are communicated to
the student over the internet. This class of Virtual Labs, at best,
mimics the real-world scenarios/experiments. Simulation based Virtual
Labs are scalable and can cater to a large number of simultaneous
users.

Remote Triggered Virtual Labs: In these Virtual Labs, the actual
experiments are triggered remotely. The output of the experiment
(being conducted remotely) is communicated back to the student over
the internet. This class of Virtual Labs, gives the student the output
of real-time experiments. Remote Triggered Virtual Labs are difficult
to scale and can cater to a limited number of users. Typically,
time-slots are booked before conducting such experiments.

Q4. Who are the intended users of the Virtual Labs? 
 The intended beneficiaries of the projects are:

   1. All students and Faculty Members of Science and Engineering
      Colleges who do not have access to good lab-facilities and/or
      instruments.
   2. High-school students, whose inquisitiveness will be triggered,
      possibly motivating them to take up higher-studies.
   3. Researchers in different institutes who can collaborate /share
      equipment and resources.
   4. Different engineering colleges, who can benefit from the content
      and related teaching resources. The project has completely
      fulfilled the requirements of the targeted beneficiaries (and
      even gone beyond). An eco-system has evolved around Virtual
      Labs, where the community has become involved in evolving and
      benefitting from the project.
Q5. How can I access the Virtual Labs?

    All Virtual Labs can be accessed through a common website:[[www.vlabs.ac.in][vlabs]] At
    the user end, a PC and broadband connectivity enables the user to
    access Virtual Labs.


Q6. Is it free to use?

Yes, it is free of cost to the user.

Q7. How I can find lab of my interest?
The Virtual labs are divided into two categories on the Virtual Labs home page (www.vlabs.ac.in)

    All Labs (Domain Wise)
    All Labs (Institute Wise)
    All Labs on Open edX

    You can click on any of the above links which are on the main menu
    under Labs option to find out labs of your perfernce .  For some
    of the labs, you will first have to register prior to conducting
    the experiments.

Q8. What are the software requirements for Virtual Labs?  Download
Links for all the software required to use the labs are provided on
each lab's homepage (wherever required). Please click on
pre-requisites link to know the information about how to download,
install and use the software.

Q9. What are the system configuration needed to run Workshops ? 


    System configuration required for running Virtual Labs:
       1. Browser: Firefox, Chrome
       2. Plugins: Flash, Java 1.6 version, and IcedTea
       3. JavaScript should be enabled on the browser
       4. No pop-up blockers
       5. Internet connection (2-4 mbps)
       6. Need an Electronics Faculty while running some of the
          adders, multiplexers experiments.

    For more details, please follow the link

Q10. Our college internet network has firewalls. Should any specific
care be taken?

    If Internet network operates behind a firewall, the communication
    ports to facilitate VLab network traffic should be
    open. Specifically ports 3306, 5900, 5902, and 8700 will need to
    be opened.

Q11. Can I use Virtual Labs at all times?

Virtual Labs are divided into two categories, namely remote triggered
labs and the simulation based labs. You can use the remote triggered
labs, as per the time mentioned on the website. The simulation based
labs are available 24x7 including weekends.

Q12. Does the Virtual Lab provide the LMS that the objectives mention?
Virtual Lab project provides a complete Leaning Management System. For
most users, Virtual Lab provides all the relevant material at one
place including the Objectives of the Experiment, Procedure, Lab
manual, Pre- and Post-experiment quizzes, additional Lab resources, in
addition to the Virtual Lab experiment. Most labs also have an
associated question bank.

Q13. How do I register for using the Virtual Labs? 


    As mentioned earlier, Virtual Labs are divided into two
    categories: simulation based labs and remote triggered
    labs. Registration requirements are different for the two
    categories.  

    Simulation based Labs: Many of the simulation based labs (marked
    with '*' require one-time registration link. You can register by
    clicking the register button on the top right corner of any
    Virtual Labs Page. However some labs that do not require
    registration can be directly accessed by following the lab links.
    
    Remote Triggered Labs: To access a remote triggered lab, a user
    has to book a slot. For booking a slot, you have to register
    yourself first and then book a slot from the slot chart. All the
    available /booked slots can be viewed on this chart. Once a
    request for slot-booking is made, all the information regarding
    the user id, password and the slot booked will be sent to the
    user's email address provided by the user at the time of
    registration. Once registered, a user can login using the same
    credentials every time. This registration has to be done by the
    user separately for each of the remote triggered virtual labs.


Q14. I already have a Physical Lab in my college/institute. What
benefit will Virtual Lab provide?

Virtual Lab is a complete Learning Management System. All the relevant
information including the theory, lab-manual, additional
web-resources, video-lectures, animated demonstrations and
self-evaluation are available at a common place. Virtual Labs can be
used in a complementary fashion to augment the efficacy of
theory-based lectures. Small projects can also be carried out using
some of the Virtual Labs. Virtual Labs can be effectively used to give
lab-demonstrations to large classes.

Q15. How does one derive the maximum benefit from Virtual Labs?


    In order to derive maximum learning experience, the users are
    advised to first read all the instructions for conducting the
    labs. There are 'step-by-step' instructions available in each lab
    to assist the users.  

Q16. When I do an experiment how do I know if the experiment I did is
    done correctly?
Virtual Labs will provide to the students the result of an experiment by one of the following methods (or possibly a combination):

   1. Modelling the physical phenomenon by a set of equations and
      carrying out simulations to yield the result of the particular
      experiment.
   2. Providing a corresponding measurement data for the Virtual Lab
      experiment based previously carried out measurements on an
      actual system.
   3. Remotely triggering an experiment in an actual lab and providing
      the student the result of the experiment through the computer
      interface.

Q17. How can a college conduct a Virtual Lab Workshop? 
For details, please follow the link

Q18. Whom can I contact if I get stuck while using Virtual Labs?  You
can email your concerns/queries to the Virtual Labs team at
users@vlabs.ac.in. Also,you can call directly on the hotline number
011-64674687 for help. 

Q19. How can I contribute to the FAQ?  Drop a mail to
poc-vlead@vlabs.ac.in with Questions (and Answers).

Q20. How can I contribute to Virtural Labs?  

vlabs-dev is the main portal for Virtual Labs Development. Please
visit the contributing section of the vlabs-dev portal.

** Virtual Labs College Cloud Edition

** Expression of Interest for Workshops
